// import type { Metadata } from "next";
// import "./globals.css";
// import Header from "./components/Header";
// import Banner from "./components/Banner";
// import { Providers } from "./providers";
// import { CartProvider } from "../contexts/CartContext"; // Điều chỉnh path
// import Footer from "./components/Footer";
// export const metadata: Metadata = {
//   title: "GNASWWW WORLDWIDE",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="vi">
//       <body>
//         {/* Bọc toàn bộ app trong CartProvider trước */}
//         <CartProvider>
//           {/* Sau đó bọc trong Providers (client) */}
//           <Providers>
//             <Header />

//             <main className="min-h-screen">{children}</main>
//             <Footer />
//           </Providers>
//         </CartProvider>
//       </body>
//     </html>
//   );
// }
// import Header from "./components/Header";
// import Banner from "./components/Banner";
// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { CartProvider } from "../contexts/CartContext";
import ShellWrapper from "./components/ShellWrapper";

export const metadata: Metadata = {
  title: "GNASWWW WORLDWIDE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="vi">
      <body>
        <CartProvider>
          <Providers>
            <ShellWrapper>{children}</ShellWrapper>
          </Providers>
        </CartProvider>
      </body>
    </html>
  );
}
